# Smasung's Day 0

## Python

### Find all the element in a list which have been repeated eg. [1,2,3,1,3,4,5,6,4] repeated elements are : [1,3,4]. What is the time complexity of the project


In [9]:
def get_repeated(nums:set):
    repeated = set()
    for num in nums:
        if nums.count(num) > 1:
            repeated.add(num)
    return repeated

In [10]:
get_repeated([1, 2, 3, 3, 4, 2, 5])

{2, 3}

TIme complexity is O[n<sup>2</sup>]

### Write a function to check if a given number is prime or not.

In [14]:
def is_prime(num:int):
    i = 2
    while i < num:
        if num % i == 0:
            return False
        i += 1
    return True

In [15]:
is_prime(2)

True

In [16]:
is_prime(10)

False

In [17]:
is_prime(7)

True

In [18]:
import random
random.randint(1, 100)

38

## Numpy
### Find the most similarity documents among 5 documents[ Document 1 , Document2, ... Documnet 5 ]
 - Create 124 dimensional random vector to create the vectors for documents. Create a numpy array containing marks for 100 students for 5 subjects
 - create random array for the above
 - print the shape and dtype of the array
 - find the min and maximum marks for the students in the 5 subjects
 - What is the mean, median, mode of the marks of each students
 - find the average marks for each of the students
 - also find the number of students who passed all the subjects?



In [34]:
import numpy as np

shape = (5, 5)
docs = np.zeros(shape)

for i in range (5):
    docs[i, i] = 0
    for j in range(i):
        num = random.randint(0, 100)
        docs[i, j] = docs[j, i] = num

print(docs)
print(docs.shape)

[[ 0. 87.  7. 82. 45.]
 [87.  0. 15. 93. 38.]
 [ 7. 15.  0. 28. 10.]
 [82. 93. 28.  0. 46.]
 [45. 38. 10. 46.  0.]]
(5, 5)


In [37]:
max(docs.flat)

93.0

In [38]:
max_index = [0, 0]
max_val = 0
for i in range (5):
    for j in range(i):
        if (docs[i, j] > max_val):
            max_val = docs[i, j]
            max_index = [i, j]

print(max_index)

[3, 1]


In [39]:
np.max(docs)

93.0